version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
    depends_on:
      - db
    volumes:
      - ${PWD}/app
    working_dir: /app
  db:
    image: postgres
    environment:
      POSTGRES_DB: local
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
